### ISSUE TITLE
Stock.dividends return unexpected values.

### ISSUE THREAD

**Issue by gourri** [danielecook/iex-api-python#13]
Hi,
Stock.dividends() returns chart response.  Is that expected behavior?
If not, need to change to call dividends API.

    def dividends(self, range='1m'):
        """
            Args:
                range - what range of data to retrieve. The variable
                        'DIVIDEND_RANGES' has possible values in addition to a date.
        """
        validate_range_set(range, RANGES)
        return self._get(f"**dividends**/{range}")

**Comment by danielecook** [comment]
Resolved with this commit 5aa930f
