### ISSUE TITLE
Problem with import

### ISSUE THREAD

**Issue by Imd5** [danielecook/iex-api-python#5]
Could you help with this issue?
c:\RH\myRH>python3 iex.py
Traceback (most recent call last):
  File "iex.py", line 1, in <module>
    from iex import stock
  File "c:\RH\myRH\iex.py", line 1, in <module>
    from iex import stock
ImportError: cannot import name 'stock' from 'iex' (c:\RH\myRH\iex.py)

**Comment by danielecook** [comment]
I'm not entirely sure what the issue is. Did you install the module with pip?

**Comment by hydroplosion** [comment]
I was getting that after installing from pip. Installing from a clone with sudo works.

**Comment by danielecook** [comment]
Interesting. I don't see this issue on MacOS. Perhaps this is windows specific?

**Comment by hydroplosion** [comment]
(original post scrapped) 
Seems I'm having capitalization issues. Was using Ubuntu in my previous comment, but on macOS the pip install doesn't seem to have the updated class names and wants lowercase i.e. _stock('aapl')_. I haven't gone back to try pip on Ubuntu, but might explain why manual install worked.

**Comment by danielecook** [comment]
Hey @hydroplosion I recently updated the package to use more traditional class names. Now the package uses `Stock` instead of `stock`. Usage is:

```
from iex import Stock
aapl = Stock("AAPL")
```

But certain classes don't have any required arguments when creating an instance. For example, the `Market` class doesn't require any arguments. Because it doesn't require any arguments, its pre-instantiated and can be imported as a class __or__ an instance:

```
from iex import Market
market = Market()
market.gainers()
```

__OR__

```
from iex import market
market.gainers()
```

Hope that helps.

**Comment by hydroplosion** [comment]
@danielecook yes, I did notice that. This is why I am thinking pip is not updated with the latest code using capital letter class names.

```
Python 3.7.0 (default, Jul 30 2018, 17:14:49) 
[Clang 9.1.0 (clang-902.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from iex import Stock
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Stock' from 'iex' (/usr/local/lib/python3.7/site-packages/iex/__init__.py)
>>> from iex import stock
>>> aapl = Stock('aapl')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'Stock' is not defined
>>> aapl = stock('aapl')
>>>
```

**Comment by danielecook** [comment]
oh I am sorry, I misunderstood. I think I need to release a new version.
