### ISSUE TITLE
Remove print(response.url) in stocks (and other print statements)

### ISSUE THREAD

**Issue by aleph0ne** [danielecook/iex-api-python#9]
Please remove print statements in the main branch. They are both noisy and do not follow the logger method, which is faster and prevents the system from hanging on logs.

Thanks!

**Comment by danielecook** [comment]
will do

**Comment by danielecook** [comment]
I believe this is fixed 37b010f452fcdcb9dff221d60124bced1a3a1442

**Comment by aleph0ne** [comment]
I actually meant this one:
https://github.com/danielecook/iex-api-python/blob/master/iex/stocks.py#L29

It prints the URL with every request, which is overwhelming.
